#+TITLE: shopt

#+BEGIN_QUOTE
shopt [-pqsu] [-o] [optname ...]
#+END_QUOTE
切换控制可选的shell行为的变量的值.
没有使用选项, 或者使用 -p 选项, 则显示一个所有可设置选项的列表, 此列表带有是否每一个已被设置的指示.
*-p* 选项导致输出以重新作为输入使用的形式显示.
其他选项有以下含义:
- *-s*     允许 (设定) 每一个 _optname_
- *-u*     禁止 (取消设定) 每一个 _optname_
- *-q*     抑制正常的输出 (安静模式) ; 返回值指示了 _optname_ 是否被设定或未被设定; 如果多个 _optname_ 被给了 *-q* ,
           且如果所有的 _optname_ 是打开的, 那么返回值将是 0; 否则返回非零;
- *-o*     限制输出 _optname_ 的值为定义在 *-o* 选项后面的 _optname_ .


如果 *-s* 或者 *-u* 被使用时不带 _optname_ 参数, 分别地限制显示这些设定的或者未设定的选项[fn:1].
除非另外说明, *shopt* 选项默认情况下是关闭的(未设定).

当列举选项时, 如果所有的 _optname_ 是打开的, 返回值是零, 否则就是非零[fn:2];
当设定或取消设定选项时, 除非 _optname_ 不是合法的shell选项, 否则返回值就是零;

*shopt* 的选项列表如下:
#+BEGIN_QUOTE
- *autocd*      :: 如果设定, 则执行名称为目录名称的命令名称，就好像它是cd命令的参数一样[fn:3];
- *cdalbe_vars* :: 如果设定, 如果给cd内置命令的参数不是一个目录，就假设它是一个变量名，变量的值是将要转换到的目录;
- *cdspell*     :: 纠正cd命令中目录名的较小拼写错误. 检查的错误包括颠倒顺序的字符, 遗漏的字符以及重复的字符.
                如果发现一处纠正, 正确的路径就打印出, 命令将继续. 只用于交互式shell; 
- *checkhash*   :: bash在试图执行一个命令前, 先在哈希表中寻找, 以确定命令是否存在。如果命令不存在, 就执行正常路径搜索;
- *checkjobs*   :: 在退出交互式shell前, *bash* 会列出任何被停止的和运行中的作业.
                如果一些作业正在运行中, 这将引起退出被推迟, 直到尝试第二个退出, 其间没有命令(被执行)(参考作业控制)[fn:4].
                如果一些作业被中止了, shell总会延迟退出;
- *checkwinsize* :: *bash* 在每一条命令后面检查窗口的大小, 并且, 如果必要的话, 会更新 *LINES* 和 *COLUMNS* 的值.
- *cmdhist* :: *bash* 尝试在同一历史条目里保存一条多行命令的所有行. 这使得多行命令的重新编辑更加容易.
- *compat31* :: **
#+END_QUOTE


* Footnotes

[fn:4] 经过尝试, 如果在执行第一个 *exit* 前, 先执行过了 jobs, 那么执行第一个exit时, 就会直接退出;
猜测是因为bash已经确认你知道当前shell有被停止或正在运行的作业, 所以第一个exit即可立即退出shell;

[fn:3] 这个选项有个坑, 如果目录名和shell中的命令名相同, 则会优先执行命令名; 只有当命令名执行失败, 才会执行目录名(这个观点我未实验过, 不过在zsh中是这样的)

[fn:2] 与上方的 *-p* 选项相照应;

[fn:1] 即打开的shopt和未打开的shopt分别显示;
